### PR TITLE
feat: add HttpClient as a part of InfluxDBClientOptions

### PR DESCRIPTION
**Pull request by tangbao0002**
Add httpclient as  a part of InfluxbOption to allow injection of custom HttpMessageHandler(https://github.com/influxdata/influxdb-client-csharp/issues/516).

_Briefly describe your proposed changes: 
  The caller can create a RestClient themselves through this constructor 'public RestClient(HttpClient httpClient, RestClientOptions options, bool disposeHttpClient = false)'. And this HttpClientMessageHandler instances will be managed by the dependency injection container.
  It is also recommended in Microsoft documentation to send HTTP requests by injecting an HTTP client instead of creating an HTTP client instance every time(https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0).

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [ ] `dotnet test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by powersj** [comment]
Hi,

Could you please file a GitHub issue and detail why you are after this functionality and what problem you hope to solve?

Thanks

**Review by bednar — CHANGES_REQUESTED** [review]
Hi @tangbao0002,

thanks for your PR and your clarification:

> The caller can create a RestClient themselves through this constructor 'public RestClient(HttpClient httpClient, RestClientOptions options, bool disposeHttpClient = false)'. And this HttpClientMessageHandler instances will be managed by the dependency injection container.
It is also recommended in Microsoft documentation to send HTTP requests by injecting an HTTP client instead of creating an HTTP client instance every time(https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0).

Before we accept the PR, there are a few requirements that must be met:

1. Please satisfy the PR checklist:
   image
1. Please add a test that covers the changes you have made

**Review by bednar — CHANGES_REQUESTED** [review]
Thanks again for your PR 👍 

Before we accept the PR, there are a few requirements that must be met:

**Review by bednar — CHANGES_REQUESTED** [review]
Please resolve the conflict for CHANGELOG.md

image

**Review by bednar — APPROVED** [review]
LGTM 👍

**Comment by alespour** [comment]
Closes #495

**Comment by alespour** [comment]
Closes #516

**Pull request merged**
