### PR TITLE
fix: use g17 format for doubles

### PR DESCRIPTION
**Pull request by powersj**
fixes: #408

## Proposed Changes

Updates the format used for doubles when building a Point to use the G17 format. This ensures 17 bits of precision and that values are successful in round-trips. This is the recommendation from the dot.net docs as well.

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [ ] `dotnet test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by davidby-influx** [comment]
My suggestion is to change the tests to round the `got` value to the precision of the `expected` value.  There may be customers who depend exact floating point comparison, but that always leads to tears.

Something like:

expected = 2.33333

got = ComputedValue()

if Math.Round(got, 5) != expected 
{
    UnhappyNoises()
}  

This may not fix everything (because midpoint rounding can [cause problems](https://learn.microsoft.com/en-us/dotnet/api/system.math.round?view=net-7.0#rounding-and-precision), but it will fix a lot of the cases.

**Comment by powersj** [comment]
Thanks for the looking at the PR!

The tests are primarily comparing two strings of line protocol. I think in those cases if we are good with updates to the floating points and it sounds like we are, I can update the expected. I'll let this this sit over night and see if Jakub chimes in.

Thanks again, I appreciate the review.

**Comment by bednar** [comment]
It looks good for me 👍

**Comment by ashishusoni** [comment]
How will this work when we add a filter to compare 
  |> filter(fn: (r) => r["_value"] >= -180)
currently it throws an error something like below 
Error – 
{

    "code": "invalid",
    "message": "runtime error @6:6-6:44: filter: cannot compile @ 6:17-6:43: unsupported binary expression string >= int"

}

**Comment by powersj** [comment]
Thank you both - the failing tests are updated, formatting corrected, and readme rebased.

**Review by davidby-influx — APPROVED** [review]
LGTM

**Pull request merged**
