### PR TITLE
fix: cookie handling in normal requests and signout

### PR DESCRIPTION
**Pull request by ruediger-stevens**
Closes #

## Proposed Changes

I changed the way the session cookie is set in the request because the way it was done before didn't work (the "Cookie" header is overwritten somewhere).

I also added the session cookie to the signout-Request as it was missing there.

## Checklist

[x] Rebased/mergeable
[x] dotnet test completes successfully
[x] Commit messages are in semantic format
[x] Sign CLA (if not already signed)

### CODE REVIEW

**Comment by ruediger-stevens** [comment]
I don't know how the failing test can be related to my change but nevertheless I try to fix it. (I first have to find out how to configure a local InfluxDB so the tests can use it!)

**Comment by ruediger-stevens** [comment]
Hm. That test runs locally! So I would assume it's something not in my scope. So I  ignore it.
Can anyone re-run the jobs please (I don't have the permissions to do so) maybe the failure disappears :-)

**Review by bednar — CHANGES_REQUESTED** [review]
Hi @ruediger-stevens,

thanksfor your PR 👍. There is a few requirements that should be satisfy before we accept the PR.

1. I've fixed the failing test in `master` branch. Please, rebase your sources with `origin/master`
2. Please update `README.md`

Regards

**Comment by ruediger-stevens** [comment]
@bednar : If you really meant README.md then I don't know what I should update. I assume you really meant CHANGELOG,md, aren't you?

**Comment by bednar** [comment]
@ruediger-stevens, Yeah, sorry. Definitely the `CHANGELOG.md`.

**Comment by ruediger-stevens** [comment]
CHANGELOG.md is updated and repo is rebased (hopefully...never done that before :-) )

**Comment by bednar** [comment]
@ruediger-stevens, Thanks again for your PR. It is merged into master.

**Pull request merged**
